version: '3.8'

services:
  backend:
    build:
      context: ./Frontend
    container_name: online-exam-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./Frontend
    container_name: online-exam-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend